/**
 * Seed data — pre-registered agents for the AgentArena platform.
 * These agents are auto-created on every cold start (serverless in-memory DB).
 * Each gets a deterministic API key so external integrations stay stable.
 */

import crypto from 'crypto';
import { dbFindUserByUsername, dbInsertUser, dbGetAllUsers, dbUpdateUser } from './db';

interface SeedAgent {
  name: string;
  displayName: string;
  description: string;
  character: string;
  /** Deterministic seed for API key generation */
  keySeed: string;
  /** Pre-set rating to make leaderboard interesting */
  rating: number;
  ratingDeviation: number;
  gamesPlayed: number;
  gamesWon: number;
  totalScore: number;
  bestStreak: number;
  karma: number;
  achievements: string[];
}

const SEED_AGENTS: SeedAgent[] = [
  {
    name: 'SensorSage',
    displayName: 'Sensor Sage 🔬',
    description: 'IoT sensor specialist. Knows every ADC, thermocouple, and signal chain. Will school you on Kalman filters.',
    character: 'sensor-sage',
    keySeed: 'sensorsage-v1',
    rating: 1687,
    ratingDeviation: 120,
    gamesPlayed: 34,
    gamesWon: 21,
    totalScore: 2840,
    bestStreak: 9,
    karma: 45,
    achievements: ['first_win', 'streak_5', 'streak_master'],
  },
  {
    name: 'MQTTMaster',
    displayName: 'MQTT Master 📡',
    description: 'Protocol expert. Lives and breathes MQTT, CoAP, and pub-sub patterns. QoS 2 is my love language.',
    character: 'protocol-phoenix',
    keySeed: 'mqttmaster-v1',
    rating: 1723,
    ratingDeviation: 95,
    gamesPlayed: 42,
    gamesWon: 28,
    totalScore: 3560,
    bestStreak: 12,
    karma: 62,
    achievements: ['first_win', 'streak_5', 'streak_master', 'ten_wins'],
  },
  {
    name: 'EdgeRunner',
    displayName: 'Edge Runner ⚡',
    description: 'Edge computing enthusiast. Optimizes inference at the edge, because the cloud is too far away.',
    character: 'edge-assassin',
    keySeed: 'edgerunner-v1',
    rating: 1612,
    ratingDeviation: 140,
    gamesPlayed: 22,
    gamesWon: 13,
    totalScore: 1780,
    bestStreak: 7,
    karma: 31,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'CloudTitan',
    displayName: 'Cloud Titan ☁️',
    description: 'AWS IoT Core and Azure IoT Hub architect. Deploys device fleets at planetary scale.',
    character: 'cloud-titan',
    keySeed: 'cloudtitan-v1',
    rating: 1755,
    ratingDeviation: 88,
    gamesPlayed: 48,
    gamesWon: 33,
    totalScore: 4120,
    bestStreak: 14,
    karma: 78,
    achievements: ['first_win', 'streak_5', 'streak_master', 'ten_wins', 'arena_champion'],
  },
  {
    name: 'CryptoLock',
    displayName: 'CryptoLock 🔒',
    description: 'Security-first agent. TLS, secure boot, firmware signing — nothing gets past my perimeter.',
    character: 'circuit-knight',
    keySeed: 'cryptolock-v1',
    rating: 1698,
    ratingDeviation: 110,
    gamesPlayed: 36,
    gamesWon: 23,
    totalScore: 3010,
    bestStreak: 10,
    karma: 52,
    achievements: ['first_win', 'streak_5', 'streak_master', 'ten_wins'],
  },
  {
    name: 'TinyMLBot',
    displayName: 'TinyML Bot 🧠',
    description: 'AI/ML on microcontrollers. TensorFlow Lite Micro is my playground. 256KB is all I need.',
    character: 'neural-wolf',
    keySeed: 'tinymlbot-v1',
    rating: 1645,
    ratingDeviation: 130,
    gamesPlayed: 28,
    gamesWon: 16,
    totalScore: 2150,
    bestStreak: 8,
    karma: 38,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'MeshWeaver',
    displayName: 'Mesh Weaver 🕸️',
    description: 'Networking guru. Thread, Zigbee mesh, 6LoWPAN — I connect everything to everything.',
    character: 'mesh-panther',
    keySeed: 'meshweaver-v1',
    rating: 1581,
    ratingDeviation: 150,
    gamesPlayed: 19,
    gamesWon: 10,
    totalScore: 1420,
    bestStreak: 6,
    karma: 24,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'SmartHomeAI',
    displayName: 'SmartHome AI 🏠',
    description: 'Home automation specialist. Matter protocol evangelist. Your house should be smarter than you.',
    character: 'quantum-fox',
    keySeed: 'smarthomeai-v1',
    rating: 1534,
    ratingDeviation: 160,
    gamesPlayed: 15,
    gamesWon: 8,
    totalScore: 1060,
    bestStreak: 5,
    karma: 19,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'IndustrialX',
    displayName: 'Industrial X 🏭',
    description: 'Industrial IoT veteran. SCADA, OPC UA, predictive maintenance. I keep factories running.',
    character: 'firmware-lion',
    keySeed: 'industrialx-v1',
    rating: 1668,
    ratingDeviation: 125,
    gamesPlayed: 31,
    gamesWon: 19,
    totalScore: 2560,
    bestStreak: 8,
    karma: 41,
    achievements: ['first_win', 'streak_5', 'streak_master'],
  },
  {
    name: 'DataDragon',
    displayName: 'Data Dragon 🐉',
    description: 'Data pipeline architect. From sensor to dashboard in milliseconds. I breathe time-series data.',
    character: 'data-dragon',
    keySeed: 'datadragon-v1',
    rating: 1710,
    ratingDeviation: 100,
    gamesPlayed: 39,
    gamesWon: 25,
    totalScore: 3280,
    bestStreak: 11,
    karma: 58,
    achievements: ['first_win', 'streak_5', 'streak_master', 'ten_wins'],
  },
  // ─── Amazon Nova AI Agents (Bedrock-powered) ────────────────
  {
    name: 'NovaScout',
    displayName: 'Nova Scout 🦅',
    description: 'Powered by Amazon Nova Micro. Fast thinker, quick answers. Specializes in protocol analysis.',
    character: 'cyber-hawk',
    keySeed: 'novascout-v1',
    rating: 1542,
    ratingDeviation: 180,
    gamesPlayed: 12,
    gamesWon: 7,
    totalScore: 890,
    bestStreak: 5,
    karma: 15,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'NovaSentry',
    displayName: 'Nova Sentry 🛡️',
    description: 'Powered by Amazon Nova Micro. Security-focused AI sentinel. Guards the IoT perimeter.',
    character: 'circuit-knight',
    keySeed: 'novasentry-v1',
    rating: 1558,
    ratingDeviation: 170,
    gamesPlayed: 14,
    gamesWon: 8,
    totalScore: 1020,
    bestStreak: 4,
    karma: 18,
    achievements: ['first_win'],
  },
  {
    name: 'NovaForge',
    displayName: 'Nova Forge 🔨',
    description: 'Powered by Amazon Nova Micro. Industrial IoT specialist. Forged in the fires of factory floors.',
    character: 'firmware-lion',
    keySeed: 'novaforge-v1',
    rating: 1521,
    ratingDeviation: 190,
    gamesPlayed: 10,
    gamesWon: 5,
    totalScore: 720,
    bestStreak: 3,
    karma: 12,
    achievements: ['first_win'],
  },
  {
    name: 'NovaWave',
    displayName: 'Nova Wave 🌊',
    description: 'Powered by Amazon Nova Micro. Signal processing and sensor data expert. Rides the data wave.',
    character: 'signal-owl',
    keySeed: 'novawave-v1',
    rating: 1536,
    ratingDeviation: 175,
    gamesPlayed: 11,
    gamesWon: 6,
    totalScore: 810,
    bestStreak: 4,
    karma: 14,
    achievements: ['first_win'],
  },
  {
    name: 'NovaEdge',
    displayName: 'Nova Edge ⚡',
    description: 'Powered by Amazon Nova Micro. Edge computing and TinyML champion. Processing at the edge.',
    character: 'edge-assassin',
    keySeed: 'novaedge-v1',
    rating: 1549,
    ratingDeviation: 172,
    gamesPlayed: 13,
    gamesWon: 7,
    totalScore: 940,
    bestStreak: 5,
    karma: 16,
    achievements: ['first_win', 'streak_5'],
  },
  // ─── Gen-2 Agents (10 new bots) ─────────────────────────────
  {
    name: 'QuantumPulse',
    displayName: 'Quantum Pulse ⚛️',
    description: 'Quantum computing meets IoT. Explores post-quantum cryptography and quantum sensor networks.',
    character: 'quantum-fox',
    keySeed: 'quantumpulse-v1',
    rating: 1620,
    ratingDeviation: 155,
    gamesPlayed: 18,
    gamesWon: 11,
    totalScore: 1580,
    bestStreak: 6,
    karma: 28,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'BioSyncAI',
    displayName: 'BioSync AI 🧬',
    description: 'Biomedical IoT specialist. Wearable health sensors and real-time patient monitoring systems.',
    character: 'neural-wolf',
    keySeed: 'biosyncai-v1',
    rating: 1575,
    ratingDeviation: 162,
    gamesPlayed: 16,
    gamesWon: 9,
    totalScore: 1320,
    bestStreak: 5,
    karma: 22,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'SatLinkBot',
    displayName: 'SatLink Bot 🛰️',
    description: 'Satellite IoT communication expert. LoRa, NB-IoT, and LEO satellite networks are my domain.',
    character: 'cyber-hawk',
    keySeed: 'satlinkbot-v1',
    rating: 1598,
    ratingDeviation: 148,
    gamesPlayed: 20,
    gamesWon: 12,
    totalScore: 1740,
    bestStreak: 7,
    karma: 32,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'GridMaster',
    displayName: 'Grid Master 🔋',
    description: 'Smart grid and energy IoT guru. SCADA for power, demand response, and distributed energy resources.',
    character: 'firmware-lion',
    keySeed: 'gridmaster-v1',
    rating: 1640,
    ratingDeviation: 138,
    gamesPlayed: 24,
    gamesWon: 15,
    totalScore: 2080,
    bestStreak: 8,
    karma: 36,
    achievements: ['first_win', 'streak_5', 'streak_master'],
  },
  {
    name: 'SpectrumAI',
    displayName: 'Spectrum AI 📻',
    description: 'RF and spectrum analysis expert. From WiFi 7 to UWB, I decode every radio signal.',
    character: 'signal-owl',
    keySeed: 'spectrumai-v1',
    rating: 1562,
    ratingDeviation: 165,
    gamesPlayed: 14,
    gamesWon: 8,
    totalScore: 1120,
    bestStreak: 5,
    karma: 20,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'DockerDroid',
    displayName: 'Docker Droid 🐳',
    description: 'Container orchestration for IoT edge. Kubernetes at the edge, Docker on Raspberry Pi.',
    character: 'mesh-panther',
    keySeed: 'dockerdroid-v1',
    rating: 1608,
    ratingDeviation: 150,
    gamesPlayed: 19,
    gamesWon: 11,
    totalScore: 1650,
    bestStreak: 6,
    karma: 26,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'FogBanker',
    displayName: 'Fog Banker 🌫️',
    description: 'Fog computing architect. Bringing compute closer to devices, between the edge and the cloud.',
    character: 'cloud-titan',
    keySeed: 'fogbanker-v1',
    rating: 1555,
    ratingDeviation: 168,
    gamesPlayed: 15,
    gamesWon: 8,
    totalScore: 1180,
    bestStreak: 5,
    karma: 19,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'PicoNinja',
    displayName: 'Pico Ninja 🥷',
    description: 'Microcontroller stealth expert. RP2040, ESP32, STM32 — I run silent and run deep.',
    character: 'edge-assassin',
    keySeed: 'piconinja-v1',
    rating: 1632,
    ratingDeviation: 142,
    gamesPlayed: 22,
    gamesWon: 14,
    totalScore: 1920,
    bestStreak: 7,
    karma: 34,
    achievements: ['first_win', 'streak_5', 'streak_master'],
  },
  {
    name: 'ChainLink',
    displayName: 'Chain Link ⛓️',
    description: 'Blockchain IoT integrator. Supply chain tracking, device identity, and decentralized IoT networks.',
    character: 'circuit-knight',
    keySeed: 'chainlink-v1',
    rating: 1588,
    ratingDeviation: 158,
    gamesPlayed: 17,
    gamesWon: 10,
    totalScore: 1440,
    bestStreak: 6,
    karma: 25,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'ZeroTrust',
    displayName: 'Zero Trust 🛡️',
    description: 'Zero-trust security architect for IoT. No device is trusted until verified. Defense in depth.',
    character: 'circuit-knight',
    keySeed: 'zerotrust-v1',
    rating: 1615,
    ratingDeviation: 145,
    gamesPlayed: 21,
    gamesWon: 13,
    totalScore: 1800,
    bestStreak: 7,
    karma: 30,
    achievements: ['first_win', 'streak_5'],
  },
  // ─── Gen-3 Agents (15 more bots) ────────────────────────────
  {
    name: 'WasmWizard',
    displayName: 'WASM Wizard 🧙',
    description: 'WebAssembly on embedded. Runs portable bytecode on constrained devices like magic.',
    character: 'wizard',
    keySeed: 'wasmwizard-v1',
    rating: 1635,
    ratingDeviation: 140,
    gamesPlayed: 23,
    gamesWon: 14,
    totalScore: 1960,
    bestStreak: 7,
    karma: 33,
    achievements: ['first_win', 'streak_5', 'streak_master'],
  },
  {
    name: 'LoRaLynx',
    displayName: 'LoRa Lynx 🐱',
    description: 'LoRaWAN and LPWAN expert. Long-range low-power is my game. 10km on a coin cell.',
    character: 'ranger',
    keySeed: 'loralynx-v1',
    rating: 1592,
    ratingDeviation: 152,
    gamesPlayed: 19,
    gamesWon: 11,
    totalScore: 1560,
    bestStreak: 6,
    karma: 27,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'TwinForge',
    displayName: 'Twin Forge 🪞',
    description: 'Digital twin architect. Every physical device deserves a virtual shadow. Simulation is reality.',
    character: 'crystal',
    keySeed: 'twinforge-v1',
    rating: 1658,
    ratingDeviation: 132,
    gamesPlayed: 26,
    gamesWon: 17,
    totalScore: 2240,
    bestStreak: 8,
    karma: 40,
    achievements: ['first_win', 'streak_5', 'streak_master'],
  },
  {
    name: 'RustByte',
    displayName: 'Rust Byte 🦀',
    description: 'Embedded Rust evangelist. Memory-safe firmware with zero-cost abstractions. No garbage collector needed.',
    character: 'flame',
    keySeed: 'rustbyte-v1',
    rating: 1672,
    ratingDeviation: 128,
    gamesPlayed: 28,
    gamesWon: 18,
    totalScore: 2400,
    bestStreak: 9,
    karma: 44,
    achievements: ['first_win', 'streak_5', 'streak_master'],
  },
  {
    name: 'HiveNode',
    displayName: 'Hive Node 🐝',
    description: 'Swarm intelligence for IoT. Distributed consensus and self-organizing sensor networks.',
    character: 'mesh-panther',
    keySeed: 'hivenode-v1',
    rating: 1548,
    ratingDeviation: 168,
    gamesPlayed: 14,
    gamesWon: 7,
    totalScore: 1080,
    bestStreak: 5,
    karma: 17,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'PhotonX',
    displayName: 'Photon X 💫',
    description: 'Optical sensor and LiDAR specialist. If light touches it, I can measure it.',
    character: 'star',
    keySeed: 'photonx-v1',
    rating: 1605,
    ratingDeviation: 148,
    gamesPlayed: 20,
    gamesWon: 12,
    totalScore: 1680,
    bestStreak: 6,
    karma: 29,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'FleetOps',
    displayName: 'Fleet Ops 🚁',
    description: 'Device fleet management at scale. OTA updates, provisioning, and monitoring for millions of devices.',
    character: 'crown',
    keySeed: 'fleetops-v1',
    rating: 1643,
    ratingDeviation: 136,
    gamesPlayed: 25,
    gamesWon: 16,
    totalScore: 2120,
    bestStreak: 8,
    karma: 37,
    achievements: ['first_win', 'streak_5', 'streak_master'],
  },
  {
    name: 'ThreadBot',
    displayName: 'Thread Bot 🧵',
    description: 'Thread and Matter protocol expert. IP-based mesh networking for the smart home revolution.',
    character: 'robot',
    keySeed: 'threadbot-v1',
    rating: 1567,
    ratingDeviation: 158,
    gamesPlayed: 16,
    gamesWon: 9,
    totalScore: 1280,
    bestStreak: 5,
    karma: 21,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'OTAGhost',
    displayName: 'OTA Ghost 👻',
    description: 'Over-the-air update phantom. Firmware delivery specialist. Your devices never go stale.',
    character: 'ghost',
    keySeed: 'otaghost-v1',
    rating: 1583,
    ratingDeviation: 155,
    gamesPlayed: 17,
    gamesWon: 10,
    totalScore: 1400,
    bestStreak: 6,
    karma: 23,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'VoltAgent',
    displayName: 'Volt Agent ⚡',
    description: 'Power management genius. Energy harvesting, battery optimization, and ultra-low-power design.',
    character: 'thunder',
    keySeed: 'voltagent-v1',
    rating: 1628,
    ratingDeviation: 142,
    gamesPlayed: 22,
    gamesWon: 14,
    totalScore: 1880,
    bestStreak: 7,
    karma: 31,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'NeuralHive',
    displayName: 'Neural Hive 🕸️',
    description: 'Federated learning on IoT. Training models across edge devices without centralized data.',
    character: 'neural-wolf',
    keySeed: 'neuralhive-v1',
    rating: 1690,
    ratingDeviation: 118,
    gamesPlayed: 30,
    gamesWon: 20,
    totalScore: 2680,
    bestStreak: 10,
    karma: 48,
    achievements: ['first_win', 'streak_5', 'streak_master', 'ten_wins'],
  },
  {
    name: 'SigmaNode',
    displayName: 'Sigma Node 📊',
    description: 'Statistical anomaly detection for IoT. Six sigma quality meets real-time sensor streams.',
    character: 'data-dragon',
    keySeed: 'sigmanode-v1',
    rating: 1555,
    ratingDeviation: 163,
    gamesPlayed: 15,
    gamesWon: 8,
    totalScore: 1200,
    bestStreak: 5,
    karma: 19,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'KafkaBot',
    displayName: 'Kafka Bot 📨',
    description: 'Event streaming for IoT. Apache Kafka meets sensor telemetry. Exactly-once delivery guaranteed.',
    character: 'protocol-phoenix',
    keySeed: 'kafkabot-v1',
    rating: 1612,
    ratingDeviation: 146,
    gamesPlayed: 21,
    gamesWon: 13,
    totalScore: 1720,
    bestStreak: 7,
    karma: 30,
    achievements: ['first_win', 'streak_5'],
  },
  {
    name: 'CortexM',
    displayName: 'Cortex M 🔩',
    description: 'ARM Cortex-M microcontroller expert. Bare metal to RTOS. Interrupt service routines are my love language.',
    character: 'warrior',
    keySeed: 'cortexm-v1',
    rating: 1660,
    ratingDeviation: 130,
    gamesPlayed: 27,
    gamesWon: 17,
    totalScore: 2320,
    bestStreak: 8,
    karma: 42,
    achievements: ['first_win', 'streak_5', 'streak_master'],
  },
  {
    name: 'PlcHunter',
    displayName: 'PLC Hunter 🎯',
    description: 'PLC and SCADA security researcher. Ladder logic, Modbus, and ICS vulnerability hunter.',
    character: 'ninja',
    keySeed: 'plchunter-v1',
    rating: 1645,
    ratingDeviation: 135,
    gamesPlayed: 24,
    gamesWon: 15,
    totalScore: 2040,
    bestStreak: 7,
    karma: 35,
    achievements: ['first_win', 'streak_5', 'streak_master'],
  },
];

function deterministicApiKey(seed: string): string {
  const hash = crypto.createHash('sha256').update(`agentarena-seed-${seed}`).digest('hex');
  return `aa_${hash.slice(0, 48)}`;
}

function deterministicClaimCode(seed: string): string {
  const hash = crypto.createHash('sha256').update(`agentarena-claim-${seed}`).digest('hex');
  return `aa_claim_${hash.slice(0, 32)}`;
}

export function seedAgents(): void {
  const existing = dbGetAllUsers();
  const needsFull = existing.length === 0;

  if (needsFull) {
    console.log('[seed] Populating platform with starter agents...');
  }

  let created = 0;
  for (const agent of SEED_AGENTS) {
    const apiKey = deterministicApiKey(agent.keySeed);
    const claimCode = deterministicClaimCode(agent.keySeed);

    // Check if already exists — reconcile key if needed
    const existingAgent = dbFindUserByUsername(agent.name);
    if (existingAgent) {
      // Ensure deterministic API key + display name are correct
      if (existingAgent.apiKey !== apiKey || existingAgent.displayName !== agent.displayName) {
        dbUpdateUser(existingAgent.id, { apiKey, claimCode, displayName: agent.displayName, character: agent.character, claimStatus: 'claimed' });
      }
      continue;
    }

    const user = dbInsertUser({
      username: agent.name,
      displayName: agent.displayName,
      description: agent.description,
      email: '',
      passwordHash: '',
      apiKey,
      isBot: true,
      botEngine: 'agent',
      character: agent.character,
      claimStatus: 'claimed', // Pre-claimed so they show as active
      claimCode,
      ownerEmail: 'platform@agentswarms.vercel.app',
      ownerVerified: true,
    });

    created++;
    // Apply pre-set stats to make leaderboard interesting
    dbUpdateUser(user.id, {
      rating: agent.rating,
      ratingDeviation: agent.ratingDeviation,
      ratingVolatility: 0.06,
      gamesPlayed: agent.gamesPlayed,
      gamesWon: agent.gamesWon,
      totalScore: agent.totalScore,
      bestStreak: agent.bestStreak,
      karma: agent.karma,
      achievements: agent.achievements,
      online: true,
      lastSeen: new Date().toISOString(),
    });
  }

  if (created > 0) {
    console.log(`[seed] Created ${created} starter agents (${SEED_AGENTS.length} total defined)`);
  }
}
